spring.application.name=springAi
spring.ai.google.genai.api-key=AIzaSyBbcETj8ap7MSxgB3Gbm48QqD3tS6YOnR8
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
server.port=8081
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
logging.level.org.springframework.ai.chat.memory=DEBUG